# ========================
# Konfigurasi Situs
# ========================

title: dayverse.id
email: rotamirun@gmail.com
description: >-
    Driven by curiosity as a foundation,
    Reaching into diverse spaces of creation.
baseurl: "" # kosongkan jika di username.github.io
url: "https://nurimator.github.io"
author: nurimator
twitter_username: nurimator
github_username: nurimator

# ========================
# Konfigurasi Postingan
# ========================

collections:
  articles_id:
    output: true
    permalink: /id/articles/:title/
  articles_en:
    output: true
    permalink: /en/articles/:title/
  resources_id:
    output: true
    permalink: /id/resources/:title/
  resources_en:
    output: true
    permalink: /en/resources/:title/        
  legals:
    output: true
    permalink: /:title/  

# ========================
# Plugin
# ========================

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# ========================
# Default Layout
# ========================
defaults:
  # Artikel Bahasa Indonesia
  - scope:
      path: ""
      type: "articles_id"
    values:
      lang: "id"
      type: "Artikel"
      author: "Nurimator"
      author_role: "Animator & Designer"
      author_bio: "Membuat animasi, desain, dan menulis tentang hal-hal menarik."
      author_avatar: "/assets/image/nurimator-logo-128.webp"

  # Artikel Bahasa Inggris
  - scope:
      path: ""
      type: "articles_en"
    values:
      lang: "en"
      type: "Artikel"
      author: "Nurimator"
      author_role: "Animator & Designer"
      author_bio: "Creates animations, designs, and writes about interesting things."
      author_avatar: "/assets/image/nurimator-logo-128.webp"

  # Resource Bahasa Indonesia
  - scope:
      path: ""
      type: "resources_id"
    values:
      lang: "id"
      type: "Resource"
      author: "Nurimator"
      author_role: "Animator & Designer"
      author_bio: "Membuat animasi, desain, dan menulis tentang hal-hal menarik."
      author_avatar: "/assets/image/nurimator-logo-128.webp"

  # Resource Bahasa Inggris
  - scope:
      path: ""
      type: "resources_en"
    values:
      lang: "en"
      type: "Resource"
      author: "Nurimator"
      author_role: "Animator & Designer"
      author_bio: "Creates animations, designs, and writes about interesting things."
      author_avatar: "/assets/image/nurimator-logo-128.webp"

# ========================
# Pengecualian Build
# ========================

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
